[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
# runner = 'gdbgui -g arm-none-eabi-gdb --gdb-args="-command=openocd.gdb"'
# runner = "arm-none-eabi-gdb -q -x openocd.gdb"
rustflags = ["-C", "link-arg=-Tlink.x"]
